services:

  api-gateway:
    build:
      context: ./apps/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      SERVICE_NAME: api-gateway
      AUTH_SERVICE_URL: http://auth-service:3000
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ./apps/auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      SERVICE_NAME: auth-service

      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: astra_platform

      REDIS_HOST: redis-cache
      REDIS_PORT: 6379

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: astra_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  postgres-data: